language: c

sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - sudo apt-get install -y libv8-dev curl libcurl4-openssl-dev
  - ./pkg-build.sh install_deps
  - ./pkg-build.sh install_github jimhester/covr

script:
 - travis_wait ./pkg-build.sh run_tests

after_success:
  - ./pkg-build.sh dump_logs_by_extension out
  - ./pkg-build.sh install_devtools
  - ./pkg-build.sh install_github HenrikBengtsson/covr
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/covr-utils/master/covr-utils.R
  - ./pkg-build.sh run_script .coveralls.R

after_failure:
 - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
      - RVERSION=devel COVERAGE=true
      - R_BUILD_ARGS="--no-build-vignettes --no-manual"
      - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
