#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://travis-ci.org/
# * r-builder: https://github.com/metacran/r-builder
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: c

env:
  global:
    - RENV="./pkg-build.sh"    # r-builder
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"


before_install:
  - echo RENV=$RENV
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/r-builder/master/pkg-build.sh;
  - chmod 755 $RENV
  - $RENV bootstrap

install:
 - $RENV install_r R.methodsS3

script:
  - travis_wait $RENV run_build
  - travis_wait $RENV run_check

after_success:
  - $RENV dump_logs_by_extension out
  - $RENV install_devtools
  - $RENV install_github HenrikBengtsson/covr
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/covr-utils/master/covr-utils.R
  - $RENV run_script .coveralls.R

after_failure:
  - $RENV dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
