#Test with Randy Zwitch solution and travis_wait

language: r

sudo: required

warnings_are_errors: false

  - travis_wait 30 ./travis-tool.sh run_tests
  
r_github_packages:
  - jimhester/covr
  
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual"

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - source shim_package.sh
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always
