#Test with Randy Zwitch solution

language: r

sudo: required

warnings_are_errors: false
  
r_github_packages:
  - jimhester/covr
  
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

after_success:
  - test $TRAVIS_R_VERSION = "3.2.4" && R CMD INSTALL $PKG_TARBALL && source shim_package.sh && Rscript -e 'covr::codecov()'
  #- R CMD INSTALL $PKG_TARBALL
  #- source shim_package.sh
  #- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
