language: r

sudo: required

r_github_packages:
  - jimhester/covr

# Build and check package

r_build_args: "travis_wait 100 --no-build-vignettes"
r_check_args: "travis_wait 100 --no-build-vignettes --as-cran"

# Report coverage rate to coveralls

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
