#Test with Randy Zwitch solution

language: r

sudo: required
  
r_github_packages:
  - jimhester/covr
  
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - source shim_package.sh
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always
