#How to use travis_wait with rTravis, webchem version:

language: c

sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - sudo apt-get install -y libv8-dev curl libcurl4-openssl-dev
  - ./pkg-build.sh install_deps
  - ./pkg-build.sh install_github jimhester/covr

script:
  - travis_wait ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

after_success:
  - if [[ ! -z "$COVERAGE" ]];then ./pkg-build.sh run_script -e 'covr::codecov(quiet = FALSE)'; fi

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
      - RVERSION=devel COVERAGE=true
      - R_BUILD_ARGS="--no-build-vignettes --no-manual"
      - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
